---
- name: TIMESCALEDB | Be sure timescaledb packages are installed
  yum:
    name: "{{ timescaledb_name }}"
    disable_gpg_check: true
    enablerepo: "TCCENTER_PostgreSQL_TimescaleDB-el8"
    state: present
